name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  sonarcloud:
    if: startsWith(github.head_ref, 'FE_') && github.event.pull_request.merged == false
    name: SonarCloud
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./comp2
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      - name: Test and coverage
        run: npm run test
      - name: SonarCloud Scan
        with:
          projectBaseDir: ./comp2
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
